# Generated by Django 3.2.2 on 2021-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.CharField(max_length=3000)),
                ('prod_pub_date', models.DateField()),
            ],
        ),
    ]
