# Generated by Django 3.2.2 on 2021-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_prod_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_company',
            field=models.CharField(default='made in china', max_length=50),
        ),
    ]
